---
output:
  html_document:
    toc: false
    code_folding: hide
runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(comment=NA, warning = FALSE, message = FALSE, echo = FALSE)
library(shinyWidgets)
library(tidyverse)
res <- readRDS("aBootClean.rds")
```

<div class="row">
<div class="col-md-4">
```{r selector}
paste("Simulation results loaded successfully.", nrow(res), "rows.")
aggLevels <- c("Alternative methods show separately", "Alternative methods aggregated", "Full detail")

pickerInput("inMetric", label = "Performance metric", choices = unique(res$criteria))
pickerInput("inDetail", label = "Aggregation Level", choices = aggLevels)
checkboxGroupButtons("inSeries", label = "Simulation Series", choices = c("Set I", "Set II", "Set III", "Set IV"), selected = "Set I")
checkboxGroupButtons("inLag"   , label = "Lag(s)", choices = c(1,3,6,12), selected = c(3, 6))

multiInput("inMethod", label = "Methods to plot", choices = unique(res$desc), selected = unique(res$desc)[-1])
observeEvent(input$inDetail, {
  if(input$inDetail == aggLevels[1])
    updateMultiInput(session, "inMethod", choices = unique(res$method), selected = unique(res$method)[-1])
  if(input$inDetail == aggLevels[2]) 
    updateMultiInput(session, "inMethod", choices = unique(res$desc), selected = unique(res$desc)[-1])
  if(input$inDetail == aggLevels[3]) 
    updateMultiInput(session, "inMethod", choices = unique(res$detail), selected = unique(res$detail)[-1])
})
```
</div>
<div class="col-md-8">
```{r viewer, out.height="900px"}
renderPlot({
  res %>%
    filter(criteria == input$inMetric, N > 70, 
           method  %in% input$inMethod, 
           lag     %in% input$inLag,
           seriesT %in% input$inSeries) %>%
    group_by(criteria, seriesT, method, N, p, lag, lagT)  %>% 
    summarise_at("value", mean) %>%
    ggplot(aes(N, value, color = method, shape = method, linetype = method)) +
      geom_line() + 
      scale_color_brewer(palette = "Set2") +
      scale_x_log10() +
      facet_grid(seriesT~lagT) +
      #scale_y_continuous(name=yaxisname, limits=limitsVector) +
      theme(legend.position="bottom",
            panel.background = element_rect(fill = "white", colour = "grey"),
            axis.text.x = element_text(angle = 90))
})
```
<hr />
Temporarily Version. Performance may be laggy due to real-time aggregation in _R_.

The imporved version with better UI and SQL backend is under development.
</div>
</div>
