# Introduction {#intro}

In real-world situation, there exists need for extracting structured information from observable mixtures of unknown signals. For example, a recording of speech may contain external noise from nearby road traffic, minor discussion among audience and constant electronic interference in addition to the speech voice itself (the "cocktail party" problem). Independence is usually one of the important statistical properties of desired processed information. 

Blind Source Separation (BSS) is set of unsupervised machine learning algorithms in terms of input being only a single data matrix. The output is usually not anticipated in advance and such algorithms mostly serve as exploratory purposes [@hyvarinen2013independent]. Compared with supervised learning like regression and classification tree, unsupervised ones are more challegning and has a tendency to be more subjective in absence of clear goal. Nevertheless, BSS and other exploratory data analysis gain increasing importance especially in online marketing and healthcare industry [@james2013introduction]. The modern information technology grants the massive quantity of data, but substracting structural insights could be great challenge. The "blind" approaches seek to provide a first glance on big data.

This thesis expands the static source separation problem into linear time-varying one that developed from previous researches, using relatively modern tools. A functional full implementation and relevant utilities in `R` will be produced. Proceeding chapters will first formulate the BSS problems and review established solutions, and then elaborate the linear time-varying structure of second order source separation. Chatper \@ref(tvsobi) provides a detailed algortihm...