# Statistical Performance of LTV-SOBI {#performance}

The accuracy of LTV-SOBI algorithm depends mostly on the source signals and mixture themselves, especially on the assumptions of uncorrelatedness and stationarity. Nevertheless, compared with SOBI, LTV-SOBI could still be embed with more accuracy losses due to its relatively more complex mixture and associating algorithms. Despite being mathematically negligible in each step, the potential losses can accumulate in autocovariance decomposition, approximate joint diagonalization and finally separating $\boldsymbol{\mathcal E}$ and $\boldsymbol \Omega_0$. Precision is further compromised when nearPD has to been applied in case of non-positive semi-definite matrices.

## Extension of Minimal Distance Index

The minimal distance index, denoted as MD, was introduce to measure the ICA algorithm performance by comparing true mixing matrix $\boldsymbol \Omega$ and estimated unmixing matrix $\widehat{\boldsymbol W}$. For a non-time-varying model, MD-index is defined as [adapted @ilmonen2010new], 

\begin{equation}
\text{MD} (\widehat{ \boldsymbol {W}}) = \frac 1 {\sqrt{p-1}} \inf\limits_{ \boldsymbol C \in \mathcal C} || \boldsymbol C \widehat{ \boldsymbol {W}} \boldsymbol \Omega - \boldsymbol I_p||
(\#eq:md)
\end{equation}

where $\mathcal C$ is the set of matrices that allows permutation and scale ambiguity, i.e. each row and column contains exactly one non-zero element. MD-index is an elegant measure for the majority of BSS algorithm, but unfortunately it could not address the time-varying structure.

The true mixing matrix $\boldsymbol \Omega_t$ is varying over the time $t=1,2,\dots,T$ in TV-SOS model, and same for $\widehat{ \boldsymbol W_1}$. Therefore, an extension to MD-index is proposed in \@ref(eq:tvmd)

\begin{equation}
\text{tvMD}(\{\widehat{ \boldsymbol W_1}, \widehat{ \boldsymbol W_2}, \dots, \widehat{ \boldsymbol W_T}\}) = \frac 1 T \sum\limits_{t=1}^T \text{MD}(\widehat{ \boldsymbol W_t})
(\#eq:tvmd)
\end{equation}

Since TV-SOS model \@ref(eq:tvsobi) determines all $\widehat{\boldsymbol W_t} = \widehat{\boldsymbol \Omega_t}^{-1}$ by the pseudo initial mixing matrix $\boldsymbol \Omega_0$ and the time varying factor $\boldsymbol{\mathcal E}$, the tvMD can be determined once LTV-SOBI algorithm is completed and the true mixing is known.

Since tvMD is technically a mean value of MD-indies over time, it has a value between $0$ and $1$ by central limit theorem, and the smaller value the better separation.

## Extension of Signal-to-Inference Ratio

In information processing, researchers tend to decompose the restored signals into four parts, namely target signals, interference from other sources, noise and artifacts from separation and evaluation algorithm. The decomposition can be written as [adapted @na2013performance; @vincent2006performance],

\begin{equation}
\boldsymbol x = \boldsymbol s_\text{signal} + \boldsymbol s_\text{interf} + \boldsymbol e_\text{noise} + \boldsymbol e_\text{artif}
(\#eq:foursignal)
\end{equation}

The target signal $\boldsymbol s_\text{signal}$ is not necessarily the exact source signal. Instead, certain transformation of source is permissible due to the identifiability issue in BSS, and it is common to permit scale and permutation transform. In fact, permutation and scaling does not usually affect signal interpretation. Some literature marks interference as $\boldsymbol e_\text{interf}$ when false mixture of sources are regarded as error even though it is originated from sources. For example, the restored signal series II mainly corresponds to source series IV, but also have partial mixture from source series I. In this case, the former is sure $\boldsymbol s_\text{signal}$, and the later should be treated as erroneous interference. Prior BSS researches, especially among information processing domain, use Signal-to-Inference Ratio (SIR) to measure the similarity between true and restored signals [@eriksson2000source; @vincent2006performance], and its definition is,

\begin{equation}
\text{SIR}= 10 \log_{10} \frac{|| \boldsymbol s_\text{target} ||^2}{|| \boldsymbol s_\text{interf}||^2}
(\#eq:sir)
\end{equation}

The LTV-SOBI algorithm by nature does not involve any external noise, and even if the noise is present in source signals, it shall become a part of true signals. Further, $\boldsymbol e_\text{artif}$ is assumed to be $\boldsymbol 0$ for simplicity. Assume the restored signal to be $\widehat{\boldsymbol x}$ and the permutation/scaling matrix $\boldsymbol C$ as defined in \@ref(eq:md); the signal decompose of \@ref(eq:foursignal) become,

\begin{equation}
\begin{aligned}
\widehat{\boldsymbol x} &= \boldsymbol {s}_\text{signal} + \boldsymbol s_\text{interf}
\\ &= \boldsymbol {Cx} + (\widehat{ \boldsymbol x} - \boldsymbol {Cx}) 
\end{aligned}
(\#eq:twosignal)
\end{equation}

Without doubt, time-varying factor should be considered, and the extension can be achieved by introducing a time index, i.e. $\widehat{\boldsymbol x}_t = \boldsymbol C_t \boldsymbol x_t + (\widehat{ \boldsymbol x}_t - \boldsymbol C_t \boldsymbol x_t)$. The SIR-index should also be slight modified to include convolution over $t=1,2,\dots,T$.

The SIR-index for TV-SOBI can be further simplified by taking $\boldsymbol C_t = \text{diag}( \boldsymbol \Omega_t \widehat{ \boldsymbol \Omega_t}^{-1})$ after a permutation fix. In practice, the permutation is found by arranging the numerically largest value to diagonal position either row-by-row or column-or-column in $\boldsymbol \Omega_t \widehat{ \boldsymbol \Omega_t}^{-1}$. Finally, the time-varying SIR-index is the measure of all diagonal value against off-diagonal items, and it is formulated as,

\begin{equation}
\text{tvSIR}= 10 \log_{10} \frac{ \sum\limits_{t=1}^T|| \text{diag}( \boldsymbol \Omega_t \widehat{ \boldsymbol \Omega_t}^{-1}) ||^2}{ \sum\limits_{t=1}^T || \text{off}( \boldsymbol \Omega_t \widehat{ \boldsymbol \Omega_t}^{-1})||^2} 
(\#eq:tvsir)
\end{equation}

where, $\boldsymbol \Omega_t \widehat{ \boldsymbol \Omega_t}^{-1} = ( \boldsymbol I + t \boldsymbol{\mathcal E})\boldsymbol \Omega_0 \big[ ( \boldsymbol I + t \widehat{\boldsymbol{\mathcal E}}) \widehat{\boldsymbol \Omega_0}\big]^{-1}$.

SIR and tvSIR does not have a direct connection to each other, but the value are comparable. SIR and tvSIR may be any real value from $-\infty$ to $\infty$, and the larger the better. It should also be noted that correlation based SIR, for example the implementation in `JADE` package [@miettinen2017blind], does not require true mixing parameters to be known, but tvSIR will always require so.

## Simulation Result

The performance of LTV-SOBI can be expected to be greatly influenced by signal inherited properties, dimension, length and the scale of mixing matrix. Despite the impossibility to address exact factors that affect performance, four sets of simulation have been conducted in _R_. Aiming to minimize potential bias, the four sets have similar sources of 3-dimensional signal that involve sinusoidal and electrocardiographic (ECG) time-series, together with another moving-average or auto-regressive series. Further, 100 repetition for each result is performed, and the arithmetic mean is reported, meaning that each point in graph \@ref(fig:resultA) and \@ref(fig:resultB) is the average performance metric from 100 simulation with given parameters.

Four sets of simulated signal mixture are further sampled into different lengths of observed mixture. For Set I of $100000 (10^5)$ total length, sample frequencies are set to be $1:1,\ 2:1,\ 4:1,\ \dots,  1024:1$ corresponding to $100000, 50000, 25000,\dots, 98$ in observed lengths. Such mehtod would be able to objectively reflect how the sampling frequencies (in terms of observed lengths) would affect performance, and it is rather important in case the mixtures are almost continuous (for example, sound). Therefore, the simulation steps can be summarized as,

1. Loop for set I, II, III and IV;

2. Loop for repitition from 1 to 100;

3. Simulate 1 source signal of size $10^4$ (or $10^5$), and generate corresponding time-varying mixture of same parameters $\boldsymbol \Omega_0$ and $\boldsymbol{\mathcal E}$;

4. Loop for sampling frequencies from $1:1$ to $1024:1$ (or $512:1$), generating observed mixture of different length;

5. Loop for different algorithm to solve the TV-SOS problem, and report performance metrics.